<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (c) 2012 NVIDIA Corporation.  All Rights Reserved.

     NVIDIA Corporation and its licensors retain all intellectual property and
     proprietary rights in and to this software and related documentation.  Any
     use, reproduction, disclosure or distribution of this software and related
     documentation without an express license agreement from NVIDIA Corporation
     is strictly prohibited.
 */
-->
<!DOCTYPE AudioConfigs [
  <!ELEMENT AudioConfigs (alsa_device)>
  <!ELEMENT alsa_device (pcm_config, playback, capture, voice-call)>
  <!ELEMENT playback (pcm_config, device, path)>
  <!ELEMENT capture (pcm_config, device, path)>
  <!ELEMENT voice-call (pcm_config, device, path)>
  <!ELEMENT device (path)>
  <!ELEMENT path (ctl, at)>
  <!ATTLIST alsa_device name (music|voice|aux|voice-call|bt-voice-call) #REQUIRED>
  <!ATTLIST alsa_device card_id CDATA #REQUIRED>
  <!ATTLIST alsa_device card_name CDATA #REQUIRED>
  <!ATTLIST alsa_device device_id CDATA #REQUIRED>
  <!ELEMENT pcm_config EMPTY>
  <!ATTLIST pcm_config rate (8000|11025|16000|22050|32000|44100|48000|64000|88200|96000|176400|192000) #IMPLIED>
  <!ATTLIST pcm_config channels (1|2|3|4|5|6|7|8) #IMPLIED>
  <!ATTLIST pcm_config bps (16|32) #IMPLIED>
  <!ATTLIST pcm_config period_size CDATA #IMPLIED>
  <!ATTLIST pcm_config period_count CDATA #IMPLIED>
  <!ATTLIST pcm_config start_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config stop_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config silence_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config avail_min CDATA #IMPLIED>
  <!ATTLIST device name (speaker|headphone|earpiece|bt-sco|aux|builtin-mic|headset-mic|bt-sco-mic|voice-call|bt-voice-call) #REQUIRED>
  <!ATTLIST path name CDATA #IMPLIED>
  <!ELEMENT param EMPTY>
  <!ATTLIST param name CDATA #REQUIRED>
  <!ATTLIST param val CDATA #REQUIRED>
  <!ELEMENT ctl EMPTY>
  <!ATTLIST ctl name CDATA #REQUIRED>
  <!ATTLIST ctl val CDATA #REQUIRED>
  <!ELEMENT at EMPTY>
  <!ATTLIST at node CDATA #REQUIRED>
  <!ATTLIST at cmd CDATA #REQUIRED>
]>
<!--
     This file is used to declare various board specific audio configs
-->

<AudioConfigs>
  <alsa_device name="music"
               card_id="-1"
               card_name="tegramax98090"
               device_id="0">
    <pcm_config rate="48000"
                channels="2"
                bps="16"
                period_size="1024"
                period_count="4"
                start_threshold="4095"
                stop_threshold="4096"
                silence_threshold="0"
                avail_min="1"/>

    <param name="ulp" val="1"/>
    <param name="HW Rates" val="48000 44100"/>
    <param name="ulp formats" val="mp3 aac"/>
    <param name="ulp rates" val="48000 44100"/>
    <param name="nvoice" val="0"/>
    <param name="I2S Master" val="1"/>

    <playback>
      <device name="headphone">
        <path name="on">
          <ctl name="Left Headphone Mixer Left DAC Switch" val="1"/>
          <ctl name="Right Headphone Mixer Right DAC Switch" val="1"/>
          <ctl name="Headphone Left Volume" val="26"/>
          <ctl name="Headphone Right Volume" val="26"/>
          <ctl name="Headphone Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
          <ctl name="Left Headphone Mixer Left DAC Switch" val="0"/>
          <ctl name="Right Headphone Mixer Right DAC Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="DAC Mono Mode" val="1"/>
          <ctl name="Right Speaker Mixer Right DAC Switch" val="1"/>
          <ctl name="Speaker Right Volume" val="26"/>
          <ctl name="Int Spk Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Right Speaker Mixer Right DAC Switch" val="0"/>
          <ctl name="Int Spk Switch" val="0"/>
          <ctl name="DAC Mono Mode" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
          <ctl name="Left Receiver Mixer Left DAC Switch" val="1"/>
          <ctl name="Right Receiver Mixer Right DAC Switch" val="1"/>
          <ctl name="Receiver Volume" val="21"/>
          <ctl name="Earpiece Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Earpiece Switch" val="0"/>
          <ctl name="Left Receiver Mixer Left DAC Switch" val="0"/>
          <ctl name="Right Receiver Mixer Right DAC Switch" val="0"/>
        </path>
      </device>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="builtin-mic">
        <path name="on">
          <ctl name="DMIC MIC Left Enable" val="1"/>
          <ctl name="DMIC MIC Right Enable" val="1"/>
          <ctl name="Int D-Mic Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="DMIC MIC Left Enable" val="0"/>
          <ctl name="DMIC MIC Right Enable" val="0"/>
          <ctl name="Int D-Mic Switch" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="DMIC MIC Left Enable" val="0"/>
          <ctl name="DMIC MIC Right Enable" val="0"/>
          <ctl name="Left ADC Mixer IN34 Switch" val="1"/>
          <ctl name="Right ADC Mixer IN34 Switch" val="1"/>
          <ctl name="ADCL Boost Volume" val="7"/>
          <ctl name="ADCR Boost Volume" val="7"/>
          <ctl name="ADCL Volume" val="12"/>
          <ctl name="ADCR Volume" val="12"/>
          <ctl name="Mic Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="DMIC MIC Left Enable" val="1"/>
          <ctl name="DMIC MIC Right Enable" val="1"/>
          <ctl name="Mic Jack Switch" val="0"/>
          <ctl name="Left ADC Mixer IN34 Switch" val="0"/>
          <ctl name="Right ADC Mixer IN34 Switch" val="0"/>
        </path>
      </device>
    </capture>
  </alsa_device>

  <alsa_device name="voice"
               card_id="-1"
               card_name="tegramax98090"
               device_id="2">
    <pcm_config rate="8000"
                channels="1"
                bps="16"
                period_size="256"
                period_count="4"
                start_threshold="1023"
                stop_threshold="1024"
                silence_threshold="0"
                avail_min="1"/>
    <playback>
      <device name="bt-sco"/>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="bt-sco-mic"/>
    </capture>
  </alsa_device>

  <alsa_device name ="aux"
             card_id="-1"
             card_name="Tegra"
             device_id="3">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>
    <param name="HW Rates" val="48000 44100"/>
    <playback>
      <device name="aux"/>
    </playback>
  </alsa_device>

  <alsa_device name="voice-call"
               card_id="-1"
               card_name="tegramax98090"
               device_id="3">
    <pcm_config rate="48000"
                channels="2"
                bps="16"
                period_size="1024"
                period_count="4"
                start_threshold="4095"
                stop_threshold="4096"
                silence_threshold="0"
                avail_min="1"/>

    <call>
      <path name="on">
        <ctl name="Call Mode Switch" val="1"/>
      </path>
      <path name="off">
        <ctl name="Call Mode Switch" val="0"/>
      </path>

      <device name="headphone">
        <path name="on">
          <ctl name="Left Headphone Mixer Left DAC Switch" val="1"/>
          <ctl name="Right Headphone Mixer Right DAC Switch" val="1"/>
          <ctl name="Headphone Left Volume" val="26"/>
          <ctl name="Headphone Right Volume" val="26"/>
          <ctl name="Headphone Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
          <ctl name="Left Headphone Mixer Left DAC Switch" val="0"/>
          <ctl name="Right Headphone Mixer Right DAC Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="DAC Mono Mode" val="1"/>
          <ctl name="Right Speaker Mixer Right DAC Switch" val="1"/>
          <ctl name="Speaker Right Volume" val="26"/>
          <ctl name="Int Spk Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Right Speaker Mixer Right DAC Switch" val="0"/>
          <ctl name="Int Spk Switch" val="0"/>
          <ctl name="DAC Mono Mode" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
          <ctl name="Left Receiver Mixer Left DAC Switch" val="1"/>
          <ctl name="Right Receiver Mixer Right DAC Switch" val="1"/>
          <ctl name="Receiver Volume" val="21"/>
          <ctl name="Earpiece Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Earpiece Switch" val="0"/>
          <ctl name="Left Receiver Mixer Left DAC Switch" val="0"/>
          <ctl name="Right Receiver Mixer Right DAC Switch" val="0"/>
        </path>
      </device>
    </call>

    <call>
      <pcm_config start_threshold="1"/>
      <device name="builtin-mic">
        <path name="on">
          <ctl name="DMIC MIC Left Enable" val="1"/>
          <ctl name="DMIC MIC Right Enable" val="1"/>
        </path>
        <path name="off">
          <ctl name="DMIC MIC Left Enable" val="0"/>
          <ctl name="DMIC MIC Right Enable" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="DMIC MIC Left Enable" val="0"/>
          <ctl name="DMIC MIC Right Enable" val="0"/>
          <ctl name="Left ADC Mixer IN34 Switch" val="1"/>
          <ctl name="Right ADC Mixer IN34 Switch" val="1"/>
          <ctl name="ADCL Boost Volume" val="7"/>
          <ctl name="ADCR Boost Volume" val="7"/>
          <ctl name="ADCL Volume" val="12"/>
          <ctl name="ADCR Volume" val="12"/>
          <ctl name="Mic Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="DMIC MIC Left Enable" val="1"/>
          <ctl name="DMIC MIC Right Enable" val="1"/>
          <ctl name="Mic Jack Switch" val="0"/>
          <ctl name="Left ADC Mixer IN34 Switch" val="0"/>
          <ctl name="Right ADC Mixer IN34 Switch" val="0"/>
        </path>
      </device>
    </call>
  </alsa_device>

  <alsa_device name ="bt-voice-call"
           card_id="-1"
           card_name="tegramax98090"
           device_id="4">
    <pcm_config rate="8000"
            channels="1"
            bps="16"
            period_size="256"
            period_count="4"
            start_threshold="1023"
            stop_threshold="1024"
            silence_threshold="0"
            avail_min="1"/>

    <call>
      <path name="on">
        <ctl name="Call Mode Switch" val="1"/>
      </path>
      <path name="off">
        <ctl name="Call Mode Switch" val="0"/>
      </path>

      <device name="bt-sco"/>
    </call>
    <call>
      <device name="bt-sco-mic"/>
    </call>
  </alsa_device>

  <alsa_device name="music"
               card_id="-1"
               card_name="tegracs42l73"
               device_id="0">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>
    <param name="ulp" val="1"/>
    <param name="ulp formats" val="mp3 aac"/>
    <param name="ulp rates" val="48000 44100"/>
    <param name="nvoice" val="0"/>
    <param name="HW Rates" val="48000 44100"/>

    <playback>
      <device name="headphone">
        <path name="on">
          <ctl name="Headphone Analog Playback Volume" val="59"/>
          <ctl name="HL-ASP Volume" val="63"/>
          <ctl name="HP Amp Switch" val="1"/>
          <ctl name="Headphone Analog Playback Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="HP Amp Switch" val="0"/>
          <ctl name="Headphone Analog Playback Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="SPK-ASP Mono Volume" val="63"/>
          <ctl name="ESL-ASP Mono Volume" val="63"/>
          <ctl name="SPK-ASP Mux" val="Left"/>
          <ctl name="ESL-ASP Mux" val="Right"/>
          <ctl name="Speakerphone Digital Playback Volume" val="216"/>
          <ctl name="Ear Speaker Digital Playback Volume" val="216"/>
          <ctl name="SPKLO Amp Switch" val="1"/>
          <ctl name="SPK Amp Switch" val="1"/>
          <ctl name="EAR Amp Switch" val="1"/>
          <ctl name="Speakerphone Digital Playback Switch" val="1"/>
          <ctl name="Ear Speaker Digital Playback Switch" val="1"/>
          <ctl name="Int Spk Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Int Spk Switch" val="0"/>
          <ctl name="SPKLO Amp Switch" val="0"/>
          <ctl name="SPK Amp Switch" val="0"/>
          <ctl name="EAR Amp Switch" val="0"/>
          <ctl name="Speakerphone Digital Playback Switch" val="0"/>
          <ctl name="Ear Speaker Digital Playback Switch" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
          <ctl name="ESL-VSP Mono Volume" val="63"/>
          <ctl name="Ear Speaker Digital Playback Volume" val="216"/>
          <ctl name="Ear Speaker Digital Playback Switch" val="1"/>
          <ctl name="EAR Amp Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="EAR Amp Switch" val="0"/>
          <ctl name="Ear Speaker Digital Playback Switch" val="0"/>
        </path>
      </device>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>

      <device name="builtin-mic">
        <path name="on">
          <ctl name="Input Path Digital Switch" val="1"/>
          <ctl name="Input Path Digital Volume" val="96"/>
          <ctl name="DMIC Left Input" val="1"/>
          <ctl name="DMIC Right Input" val="1"/>
          <ctl name="ASP-IP Volume" val="63"/>
          <ctl name="Int D-Mic Switch" val="1"/>
          <ctl name="IP Digital Swap/Mono Select" val="Stereo"/>
        </path>
        <path name="off">
          <ctl name="Int D-Mic Switch" val="0"/>
          <ctl name="Input Path Digital Switch" val="0"/>
          <ctl name="DMIC Left Input" val="0"/>
          <ctl name="DMIC Right Input" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="Input Path Digital Switch" val="1"/>
          <ctl name="Input Path Digital Volume" val="96"/>
          <ctl name="Input PGA Analog Volume" val="24"/>
          <ctl name="ADC Left Input" val="1"/>
          <ctl name="ADC Right Input" val="1"/>
          <ctl name="PGA Right Mux" val="Mic 2"/>
          <ctl name="MIC Preamp Switch" val="0"/>
          <ctl name="ADC A Boost Volume" val="0"/>
          <ctl name="ADC B Boost Volume" val="0"/>
          <ctl name="ASP-IP Volume" val="63"/>
          <ctl name="IP Digital Swap/Mono Select" val="Mono"/>
          <ctl name="Headset Mic Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Headset Mic Switch" val="0"/>
          <ctl name="ADC Right Input" val="0"/>
          <ctl name="ADC Left Input" val="0"/>
          <ctl name="PGA Right Mux" val="Line B"/>
        </path>
      </device>
    </capture>
  </alsa_device>

  <alsa_device name="voice"
               card_id="-1"
               card_name="tegracs42l73"
               device_id="2">
    <pcm_config rate="8000"
                channels="1"
                bps="16"
                period_size="256"
                period_count="4"
                start_threshold="1023"
                stop_threshold="1024"
                silence_threshold="0"
                avail_min="1"/>
    <playback>
      <device name="bt-sco"/>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="bt-sco-mic"/>
    </capture>
  </alsa_device>

  <alsa_device name ="voice-call"
           card_id="-1"
           card_name="tegracs42l73"
           device_id="3">
    <pcm_config rate="16000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>

    <call>
      <path name="on">
        <ctl name="Call Mode Switch" val="1"/>
      </path>
      <path name="off">
        <ctl name="Call Mode Switch" val="0"/>
      </path>

      <device name="headphone">
        <path name="on">
          <ctl name="Headphone Analog Playback Volume" val="59"/>
          <ctl name="HL-VSP Volume" val="63"/>
          <ctl name="HP Amp Switch" val="1"/>
          <ctl name="Headphone Analog Playback Switch" val="1"/>
          <at node="/dev/ttyACM2" cmd="at%iaudcnf=1\r\n"/>
        </path>
        <path name="off">
          <ctl name="HP Amp Switch" val="0"/>
          <ctl name="Headphone Analog Playback Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="SPK-VSP Mono Volume" val="63"/>
          <ctl name="ESL-VSP Mono Volume" val="63"/>
          <ctl name="Speakerphone Digital Playback Volume" val="216"/>
          <ctl name="Ear Speaker Digital Playback Volume" val="216"/>
          <ctl name="SPKLO Amp Switch" val="1"/>
          <ctl name="SPK Amp Switch" val="1"/>
          <ctl name="Speakerphone Digital Playback Switch" val="1"/>
          <ctl name="Ear Speaker Digital Playback Switch" val="1"/>
          <ctl name="Int Spk Switch" val="1"/>
          <at node="/dev/ttyACM2" cmd="at%iaudcnf=2\r\n"/>
        </path>
        <path name="off">
          <ctl name="Int Spk Switch" val="0"/>
          <ctl name="SPKLO Amp Switch" val="0"/>
          <ctl name="SPK Amp Switch" val="0"/>
          <ctl name="Speakerphone Digital Playback Switch" val="0"/>
          <ctl name="Ear Speaker Digital Playback Switch" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
          <ctl name="ESL-VSP Mono Volume" val="63"/>
          <ctl name="Ear Speaker Digital Playback Volume" val="216"/>
          <ctl name="Ear Speaker Digital Playback Switch" val="1"/>
          <ctl name="EAR Amp Switch" val="1"/>
          <at node="/dev/ttyACM2" cmd="at%iaudcnf=0\r\n"/>
        </path>
        <path name="off">
          <ctl name="EAR Amp Switch" val="0"/>
          <ctl name="Ear Speaker Digital Playback Switch" val="0"/>
        </path>
      </device>
    </call>
    <call>
      <device name="builtin-mic">
        <path name="on">
          <ctl name="Input Path Digital Switch" val="1"/>
          <ctl name="Input Path Digital Volume" val="96"/>
          <ctl name="DMIC Left Input" val="1"/>
          <ctl name="DMIC Right Input" val="1"/>
          <ctl name="ADC A Boost Volume" val="1"/>
          <ctl name="ADC B Boost Volume" val="1"/>
          <ctl name="VSP-IP Volume" val="63"/>
          <ctl name="VSPOUT Mono/Stereo Select" val="Stereo"/>
          <ctl name="IP Digital Swap/Mono Select" val="Stereo"/>
          <ctl name="Int D-Mic Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Int D-Mic Switch" val="0"/>
          <ctl name="Input Path Digital Switch" val="0"/>
          <ctl name="DMIC Right Input" val="0"/>
          <ctl name="DMIC Left Input" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="Input Path Digital Switch" val="1"/>
          <ctl name="Input Path Digital Volume" val="96"/>
          <ctl name="Input PGA Analog Volume" val="24"/>
          <ctl name="ADC Left Input" val="1"/>
          <ctl name="ADC Right Input" val="1"/>
          <ctl name="ADC A Boost Volume" val="0"/>
          <ctl name="ADC B Boost Volume" val="0"/>
          <ctl name="PGA Right Mux" val="Mic 2"/>
          <ctl name="MIC Preamp Switch" val="0"/>
          <ctl name="VSP-IP Volume" val="63"/>
          <ctl name="VSPOUT Mono/Stereo Select" val="Mono"/>
          <ctl name="IP Digital Swap/Mono Select" val="Mono"/>
          <ctl name="Headset Mic Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Headset Mic Switch" val="0"/>
          <ctl name="ADC Right Input" val="0"/>
          <ctl name="ADC Left Input" val="0"/>
          <ctl name="PGA Right Mux" val="Line B"/>
        </path>
      </device>
    </call>
  </alsa_device>

   <alsa_device name ="bt-voice-call"
           card_id="-1"
           card_name="tegracs42l73"
           device_id="4">
    <pcm_config rate="8000"
            channels="1"
            bps="16"
            period_size="256"
            period_count="4"
            start_threshold="1023"
            stop_threshold="1024"
            silence_threshold="0"
            avail_min="1"/>

    <call>
      <path name="on">
        <at node="dev/ttyACM2" cmd="at%iaudcnf=4\r\n"/>
        <ctl name="Call Mode Switch" val="1"/>
      </path>
      <path name="off">
        <ctl name="Call Mode Switch" val="0"/>
      </path>

      <device name="bt-sco"/>
    </call>
    <call>
      <device name="bt-sco-mic"/>
    </call>
  </alsa_device>

  <alsa_device name="music"
             card_id="-1"
             card_name="tegraaic326x"
             device_id="0">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>

    <param name="ulp" val="1"/>
    <param name="ulp formats" val="mp3 aac"/>
    <param name="ulp rates" val="48000 44100"/>
    <param name="I2S Master" val="0"/>
    <param name="nvoice" val="0"/>
    <param name="HW Rates" val="48000 44100"/>

    <path>
      <ctl name="ASI1LIN Route" val="ASI1 Left In"/>
      <ctl name="ASI1RIN Route" val="ASI1 Right In"/>
      <ctl name="ASI3LIN Route" val="ASI3 Left In"/>
      <ctl name="ASI3RIN Route" val="ASI3 Right In"/>
      <ctl name="DAC MiniDSP IN1 Route" val="ASI1 In"/>
      <ctl name="DAC MiniDSP IN3 Route" val="ASI3 In"/>
      <ctl name="ASI1OUT Route" val="ADC MiniDSP Out1"/>
      <ctl name="ASI3OUT Route" val="ADC MiniDSP Out3"/>
      <ctl name="PCM Playback Volume" val="127"/>
      <ctl name="MicPGA Volume Control" val="60"/>
      <ctl name="PCM Capture Volume" val="24"/>
      <ctl name="HeadPhone Driver Amplifier Volume" val="7"/>
      <ctl name="Speaker Amplifier Volume" val="3"/>
      <ctl name="Receiver Amplifier Volume" val="10"/>
      <ctl name="LO Left Mixer Left DAC Playback Switch" val="1"/>
      <ctl name="LO Right Mixer Right DAC Playback Switch" val="1"/>
    </path>

    <playback>
      <path name="on">
        <ctl name="Codec Firmware Setmode" val="Low Power Playback" mode="AUDIO_MODE_NORMAL" srate="48000"/>
        <ctl name="Codec Firmware Setmode" val="Low Power Playback44k" mode="AUDIO_MODE_NORMAL" srate="44100"/>
        <ctl name="Codec Firmware Setmode" val="Music Playback Rec 16KHz" mode="AUDIO_MODE_IN_COMMUNICATION" srate="16000"/>
        <ctl name="Codec Firmware Setmode" val="VoIP Call Receiver" mode="AUDIO_MODE_IN_COMMUNICATION" srate="48000"/>
      </path>
      <path name="off">
        <ctl name="Codec Firmware Setmode" val="Low Power Playback" mode="AUDIO_MODE_NORMAL" srate="48000"/>
        <ctl name="Codec Firmware Setmode" val="Low Power Playback44k" mode="AUDIO_MODE_NORMAL" srate="44100"/>
        <ctl name="Codec Firmware Setmode" val="Music Playback Rec 16KHz" mode="AUDIO_MODE_IN_COMMUNICATION" srate="16000"/>
        <ctl name="Codec Firmware Setmode" val="VoIP Call Receiver" mode="AUDIO_MODE_IN_COMMUNICATION" srate="48000"/>
      </path>

      <device name="headphone">
        <path name="on">
          <ctl name="HP Right Mixer LO Right-B1 Playback Volume" val="127"/>
          <ctl name="HP Left Mixer LO Left-B1 Playback Volume" val="127"/>
          <ctl name="Headphone Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
          <ctl name="HP Left Mixer LO Left-B1 Playback Volume" val="0"/>
          <ctl name="HP Right Mixer LO Right-B1 Playback Volume" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="SPK Left Mixer LO Left Playback Volume" val="127"/>
          <ctl name="SPK Right Mixer LO Right Playback Volume" val="127"/>
          <ctl name="Int Spk Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Int Spk Switch" val="0"/>
          <ctl name="SPK Left Mixer LO Left Playback Volume" val="0"/>
          <ctl name="SPK Right Mixer LO Right Playback Volume" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
          <ctl name="REC Mixer LO Left-B2 Playback Volume" val="127"/>
          <ctl name="REC Mixer LO Right-B2 Playback Volume" val="127"/>
          <ctl name="Earpiece Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Earpiece Switch" val="0"/>
          <ctl name="REC Mixer LO Left-B2 Playback Volume" val="0"/>
          <ctl name="REC Mixer LO Right-B2 Playback Volume" val="0"/>
        </path>
      </device>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>

      <device name="builtin-mic">
        <path name="on">
          <ctl name="Codec Firmware Setmode" val="Voice Record On Board Mic" mode="AUDIO_MODE_NORMAL" srate="48000"/>
          <ctl name="Codec Firmware Setmode" val="Music Playback Rec 16KHz" mode="AUDIO_MODE_IN_COMMUNICATION" srate="16000"/>
          <ctl name="Right ADC Route" val="Digital"/>
          <ctl name="Left ADC Route" val="Digital"/>
          <ctl name="Int Mic Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Right ADC Route" val="Analog"/>
          <ctl name="Left ADC Route" val="Analog"/>
          <ctl name="Int Mic Switch" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="Codec Firmware Setmode" val="Voice Record Headset Mic" mode="AUDIO_MODE_NORMAL" srate="48000"/>
          <ctl name="Codec Firmware Setmode" val="Music Playback Rec 16KHz" mode="AUDIO_MODE_IN_COMMUNICATION" srate="16000"/>
          <ctl name="Right ADC Route" val="Analog"/>
          <ctl name="Left ADC Route" val="Analog"/>
          <ctl name="Left Input Mixer IN1 Left Capture Switch" val="1"/>
          <ctl name="Left Input Mixer CM1 Left Capture Switch" val="1"/>
          <ctl name="Input CM mode" val="1"/>
          <ctl name="Mic Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Input CM mode" val="0"/>
          <ctl name="Left Input Mixer IN1 Left Capture Switch" val="0"/>
          <ctl name="Left Input Mixer CM1 Left Capture Switch" val="0"/>
          <ctl name="Mic Jack Switch" val="0"/>
        </path>
      </device>
    </capture>
  </alsa_device>

  <alsa_device name="voice"
               card_id="-1"
               card_name="tegraaic326x"
               device_id="2">
    <pcm_config rate="8000"
                channels="1"
                bps="16"
                period_size="256"
                period_count="4"
                start_threshold="1023"
                stop_threshold="1024"
                silence_threshold="0"
                avail_min="1"/>
    <playback>
      <device name="bt-sco"/>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="bt-sco-mic"/>
    </capture>
  </alsa_device>

  <alsa_device name ="voice-call"
           card_id="-1"
           card_name="tegraaic326x"
           device_id="3">
    <pcm_config rate="16000"
                channels="2"
                bps="16"
                period_size="256"
                period_count="4"
                start_threshold="1023"
                stop_threshold="1024"
                silence_threshold="0"
                avail_min="1"/>
    <path>
      <ctl name="ASI3OUT Route" val="ADC MiniDSP Out3"/>
      <ctl name="ASI1OUT Route" val="ADC MiniDSP Out1"/>
      <ctl name="DAC MiniDSP IN1 Route" val="ASI1 In"/>
      <ctl name="DAC MiniDSP IN3 Route" val="ASI3 In"/>
      <ctl name="ASI3LIN Route" val="ASI3 Left In"/>
      <ctl name="ASI3RIN Route" val="ASI3 Right In"/>
      <ctl name="ASI1LIN Route" val="ASI1 Left In"/>
      <ctl name="ASI1RIN Route" val="ASI1 Right In"/>
      <!--playback paths-->
      <ctl name="PCM Playback Volume" val="127"/>
      <ctl name="HeadPhone Driver Amplifier Volume" val="7"/>
      <ctl name="Speaker Amplifier Volume" val="3"/>
      <ctl name="Receiver Amplifier Volume" val="30"/>
      <ctl name="LO Left Mixer Left DAC Playback Switch" val="1"/>
      <ctl name="LO Right Mixer Right DAC Playback Switch" val="1"/>
      <!--capture paths-->
      <ctl name="PCM Capture Volume" val="24"/>
      <ctl name="MICBIAS EXT Power Level" val="0"/>
    </path>
    <call>
        <path name="on">
          <ctl name="MicPGA Volume Control" val="30"/>
          <ctl name="Call Mode Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Call Mode Switch" val="0"/>
          <ctl name="Codec Firmware Setmode" val="Low Power Playback44k"/>
        </path>